// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Mobile   string `json:"mobile"`
}

// login request | 登录参数
// swagger:model LoginReq
type LoginReq struct {
	// User Name | 用户名
	// Required: true
	// Max length: 20
	Username string `json:"username"`
	// Password | 密码
	// Required: true
	// Min length: 6
	// Max length: 30
	Password string `json:"password"`
}

type UserInfoReq struct {
	Id string `path:"id"`
}

type UserInfoReply struct {
	Name        string   `json:"name"`
	Age         int      `json:"age"`
	Birthday    string   `json:"birthday"`
	Description string   `json:"description"`
	Tag         []string `json:"tag"`
}

type UserSearchReq struct {
	KeyWord string `form:"keyWord"`
}
